CREATE TABLE IF NOT EXISTS usuarios (id INTEGER PRIMARY KEY AUTOINCREMENT, nome VARCHAR(45), email VARCHAR(145), sexo VARCHAR(20), celular VARCHAR(15));

CREATE TABLE IF NOT EXISTS tipos (id INTEGER PRIMARY KEY AUTOINCREMENT, descricao VARCHAR(45), cor VARCHAR(7), operador CHAR(1));

CREATE TABLE IF NOT EXISTS contas (id INTEGER PRIMARY KEY AUTOINCREMENT, descricao VARCHAR(45));

CREATE TABLE IF NOT EXISTS lancamentos (id INTEGER PRIMARY KEY AUTOINCREMENT, valor DECIMAL(5,2), data DATE, descricao VARCHAR(45), observacao TINYTEXT, lancamentoId INT, tipoId INT, contaId INT, usuarioCadastro INT, dataCadastro TIMESTAMP, usuarioAtualizacao INT, dataAtualizacao TIMESTAMP);
